# Font
font_family      MesloLGM Nerd Font Mono
bold_font        MesloLGM Nerd Font Mono Bold
italic_font      MesloLGM Nerd Font Mono Italic
bold_italic_font MesloLGM Nerd Font Mono Bold Italic
font_size        13.0

# Window
window_padding_width    14
background_opacity      0.96
confirm_os_window_close 0

# Tokyo Night colors
background  #1a1b26
foreground  #c0caf5
cursor      #c0caf5
cursor_text_color #1a1b26
selection_background #364a82
selection_foreground #c0caf5

# Black
color0  #15161e
color8  #414868

# Red
color1  #f7768e
color9  #f7768e

# Green
color2  #9ece6a
color10 #9ece6a

# Yellow
color3  #e0af68
color11 #e0af68

# Blue
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #a9b1d6
color15 #c0caf5

# Misc
url_color        #7aa2f7
tab_bar_style    powerline
active_tab_background   #7aa2f7
active_tab_foreground   #1a1b26
inactive_tab_background #24283b
inactive_tab_foreground #565f89
